== Setup
IMPORTANT: This project leverages Google Firebase as main backend and Angular as frontend with Angular CLI.

*A note on hosting this project:*
The simplest way to host the project is directly on Firebase. However, you can also host it on any host for yourself, but the project itself always relies on
 the usage of Firebase services!


The next sub-sections will cover setting up everything required to run the project either locally or on a server:

=== Clone the source
Clone the source code and go into that folder:
[source]
-------------------
git clone https://github.com/dArignac/treasury.git
cd treasury
-------------------

=== Environment settings
Copy `treasury/src/environments/environment.ts` to

* `treasury/src/environments/environment.dev.ts` for *development* environment
* `treasury/src/environments/environment.prod.ts` for *production* environment (on how to deploy, see chapter <<Deployment>>)
** adjust the value of `production` from `false` to `true`

==== Add an imprint and data privacy statement
If you live in Germany than you need to add an imprint if you host this application publically. As European Union citizen you also need a data privacy declaration. I don't know how it applies to other countries.

*The content of the imprint and data privacy document is in your own responsibility!*

_Treasury_ has a document describing which user data and external tools are used. You should incorporate this into your data privacy content: https://github.com/dArignac/treasury/blob/master/PRIVACY-POLICY.md

Anyway, _treasury_ has prepared an imprint component for both imprint and data privacy. To enable it, change the value of `enableImprint` to `true`. Then copy the file `treasury/src/app/imprint/imprint.component.tmpl` to `treasury/src/app/imprint/imprint.component.html` and add your imprint and data privacy text into it (between the `div` tags).

=== Firebase project setup
* go to the https://console.firebase.google.com/u/0/[Firebase console] and create a new project
* enable and configure *Authentication* (treasury is developed with Google auth only - any other auth should work but was not tested)
* under *Database* enable Cloud Firestore
* enable *Hosting* if you want to host _treasury_ directly on Firebase

=== Firebase environment settings
Within the Firebase Console choose the settings gear icon and in the dropdown choose "Project settings".
Under "My Apps" click the icon with _"</>"_ and grab the values to update the development and/or production environment file you created before with it:

[source,typescript]
-------------------
// NOTE other environment settings are stripped
export const environment = {
  firebase: {
    apiKey: '',
    authDomain: '',
    databaseURL: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: ''
  }
};
-------------------

=== Firebase local setup
To be able to push the project contents to your newly created Firebase project, you need to install the Firebase CLI on your local machine. We install it into the global npm space of your machine.

Therefore run the following:

[source]
--------
npm install --global firebase-tools firebase firebase-functions@latest firebase-admin@latest
--------

NOTE: The following is not necessary if you do not want to publish to Firebase.

Setup Firebase locally as follows. +
All required files are already part of the project (`firebase.json`, `firestore.indexes.json`, `firestore.rules`), we just let Firebase create the `.firebaserc`.

When the `firebase init` command asks what to setup, choose *Functions* and *Firestore*. Don't overwrite the files that are identified as already existing. Also do not install the `npm` dependencies:

[source]
--------
firebase login
firebase init
--------

=== The Movie DB setup
* sign up for an TMDB account at https://www.themoviedb.org/account/signup[The Movie DB] or https://www.themoviedb.org/login[log into an existing one]
* goto https://www.themoviedb.org/settings/api and grab the `API Key (v3 auth)`
* add this value to `treasury/src/environments/environment.dev.ts` (and for production in `environment.prod.ts`) under `environment.themoviedb.apiKey`

[source,typescript]
-------------------
// NOTE: other environment values are stripped
export const environment = {
  ...
  themoviedb: {
    apiKey: 'YOUR-API-KEY',
    ...
  }
  ...
};
-------------------

=== Treasury setup
Now that you have configured the Firebase and TMDB settings, you can install the required packages of _treasury_. Therefore go to the *treasury* folder (if you cloned the project like described before, the path is `<clone-root>/treasury/treasury`):

[source]
--------
npm install --global @angular/cli
npm i
--------

This installs https://cli.angular.io/[Angular CLI] in the global npm scope and installs all required packages of _treasury_ locally (and thus created the `node_modules` folder).

=== Run in development mode
For development, simply run `npm run serve` from the treasury folder and open your browser at http://localhost:4444
