== Deployment

=== Sentry setup (optional)
* for error logging in the live environment you *can* use Sentry
* therefore get an account at https://sentry.io/signup/
* add your sentry Public DSN to `treasury/src/environments/environment.prod.ts` in `environment.sentryDSN` (get it under _"Data"_ > _"Error tracking"_)
* Sentry will only be used in the `prod` environment

=== Deployment preparation
==== Compile for production
For Firebase hosting as well as custom hosting you need to compile the application to production mode beforehand:

[source]
--------
cd treasury
ng build --prod
--------

This will output the application for production environment in the folder `treasury/dist`.

==== Initialize firebase
From the project root, run:

[source]
--------
firebase deploy --only functions,firestore
--------

This will initialize the Cloud Functions and Cloud Firestore (the database).

=== Firebase Hosting
To deploy to Firebase, simply go to the project root and run `firebase deploy`.

=== Custom Hosting
Put the contents of the `treasury/dist` folder somewhere onto your server and configure it to serve it.

IMPORTANT: I never tested this, if you have any issues, please file a https://github.com/dArignac/treasury/issues/new[Github issue]
