language: node_js
node_js:
  - "node"

addons:
  sonarcloud:
    organization: "darignac-github"

cache:
  yarn: true
  directories:
    - '$HOME/.sonar/cache'
    - node_modules

stages:
  - test

script:
  - git fetch --unshallow
  - yarn
  - NODE_PATH=$HOME/node_modules sonar-scanner
