language: node_js
node_js:
  - "node"

addons:
  sonarcloud:
    organization: "darignac-github"

services:
  - docker

cache:
  yarn: true
  directories:
    - '$HOME/.sonar/cache'
    - node_modules

stages:
  - test
  - name: make-docs
    if: branch = master
  - name: deploy-docs
    if: branch = master

script:
  - git fetch --unshallow
  - yarn
  - NODE_PATH=$HOME/node_modules sonar-scanner

jobs:
  include:
    - stage: make-docs
      before_install:
        - docker pull darignac/asciidoctor
      script:
        - make documentation
      after_error:
        - docker logs asciidoc-to-html
      after_failure:
        - docker logs asciidoc-to-html
    - stage: deploy-docs
      script: "Deploying to Github Pages"
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: documents
        target_branch: gh-pages
        github_token: $GITHUB_TOKEN
        on:
          branch: master
