branches:
  only:
    - master

dist: trusty

addons:
  sonarcloud:
    organization: "darignac-github"

services:
  - docker

cache:
  directories:
    - '$HOME/.sonar/cache'

before_install:
  - docker pull darignac/asciidoctor

script:
  - git fetch --unshallow
  - make documentation
  - npm install typescript@2.9.2
  - NODE_PATH=$HOME/node_modules sonar-scanner

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: documents
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN
  on:
    branch: master