dist: trusty

addons:
  sonarcloud:
    organization: "darignac-github"

cache:
  yarn: true
  directories:
    - '$HOME/.sonar/cache'
    - node_modules

stages:
  - test
  - name: documentation
    if: branch = master

jobs:
  include:
    - stage: test
      name: "SonarCloud analysis"
      install: yarn add typescript@2.9.2
      script:
        - git fetch --unshallow
        - NODE_PATH=$HOME/node_modules sonar-scanner
    - stage: documentation
      services:
        - docker
      before_install: docker pull darignac/asciidoctor
      after_error: docker logs asciidoc-to-html
      after_failure: docker logs asciidoc-to-html
      name: "Generate AsciiDoc documentation"
      script: make documentation
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: documents
        target_branch: gh-pages
        github_token: $GITHUB_TOKEN
        on:
          branch: master
