dist: trusty

addons:
  sonarcloud:
    organization: "darignac-github"

cache:
  yarn: true
  directories:
    - '$HOME/.sonar/cache'
    - node_modules

stages:
  - test

script:
  - git fetch --unshallow
  - yarn add typescript@2.9.2
  - NODE_PATH=$HOME/node_modules sonar-scanner
