dist: bionic

addons:
  sonarcloud:
    organization: 'darignac-github'

cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"
    - "$HOME/.sonar/cache"
    - "$TRAVIS_BUILD_DIR/node_modules"

stages:
  - jasmine
  - name: documentation
    if: branch = master

after_script:
  - echo "after script is running..."

jobs:
  include:
    - stage: jasmine
      name: "Jasmine tests & Code analysis"
      install:
        - npm install typescript@2.9.2
      script:
        - echo "TODO run the jasmine stuff with npm ci (from treasury dir) and npm run ng test --configuration ci"
        - git fetch --unshallow
        - NODE_PATH=$HOME/node_modules sonar-scanner
    - stage: documentation
      services:
        - docker
      before_install: docker pull darignac/asciidoctor
      after_error: docker logs asciidoc-to-html
      after_failure: docker logs asciidoc-to-html
      name: "Generate AsciiDoc documentation"
      script: make documentation
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: documents
        target_branch: gh-pages
        github_token: $GITHUB_TOKEN
        on:
          branch: master
