dist: trusty

addons:
  sonarcloud:
    organization: "darignac-github"

cache:
  yarn: true
  directories:
    - '$HOME/.sonar/cache'
    - node_modules

jobs:
  include:
    - stage: test
      name: "SonarCloud analysis"
      install: yarn add typescript@2.9.2
      script:
        - git fetch --unshallow
        - NODE_PATH=$HOME/node_modules sonar-scanner
    - stage: documentation
      script: echo "Will build documentation soon"
