== Development

=== Workflows
* use `ng update` to update Angular stuff
* use `ng generate component --project=treasury` to create a new component
* use `npm outdated` to find outdated packages and update them with `npm update --save <packagename>`
* to update the `functions`, use
[source]
--------
npm i firebase-functions@latest --save
npm i firebase-admin@latest --save-exact
npm i -g firebase-tools
--------

=== Continuous Integration
Uses https://travis-ci.org/dArignac/treasury[Travis-CI] for automated pipeline. Each single step can also be run locally.

The steps are:

* Sonar analysis
* Jasmine tests *(TBD!)*
* build documentation (what you're currently reading)


==== Workflows
===== SonarCloud
* runs the sonar-scanner and sends the results to the https://sonarcloud.io/dashboard?id=dArignac_treasury[configured SonarCloud instance] (via the `SONAR_TOKEN` environment variable)
* Prerequisites (are covered in `.travis.yml`):
** the addon `sonarcloud` needs to be defined in the `addons` section of `.travis-yml`
** the folder `$HOME/.sonar/cache` needs to be cached in `.travis-yml`
** an unshallowed git copy must be given, otherwise SonarCloud complains about not being able to reference commits
*** `git fetch --unshallow` needs to be run before everything else in `scripts` in `.travis-yml`

=== References
* https://github.com/angular/angularfire2 for Angular-Firebase bindings
* https://github.com/trimox/angular-mdc-web for Material Design
