import { NgModule } from '@angular/core';
import {
  MdcButtonModule,
  // MdcCardModule,
  // MdcCheckboxModule,
  // MdcDialogModule,
  MdcDrawerModule,
  // MdcElevationModule,
  // MdcFabModule,
  // MdcFormFieldModule,
  MdcIconButtonModule,
  // MdcIconModule,
  MdcLinearProgressModule,
  MdcListModule,
  // MdcMenuModule,
  // MdcRadioModule,
  // MdcRippleModule,
  MdcSelectModule,
  // MdcSliderModule,
  MdcSnackbarModule,
  // MdcSwitchModule,
  MdcTextFieldModule,
  // MdcToolbarModule,
  MdcTopAppBarModule,
  // MdcTypographyModule,
} from '@angular-mdc/web';


@NgModule({
  exports: [
    MdcButtonModule,
    // MdcCardModule,
    // MdcCheckboxModule,
    // MdcDialogModule,
    MdcDrawerModule,
    // MdcElevationModule,
    // MdcFabModule,
    // MdcFormFieldModule,
    MdcIconButtonModule,
    // MdcIconModule,
    MdcLinearProgressModule,
    MdcListModule,
    // MdcMenuModule,
    // MdcRadioModule,
    // MdcRippleModule,
    MdcSelectModule,
    // MdcSliderModule,
    MdcSnackbarModule,
    // MdcSwitchModule,
    MdcTextFieldModule,
    // MdcToolbarModule,
    MdcTopAppBarModule,
    // MdcTypographyModule,
  ]
})
export class MaterialModule {}
