=== Firebase setup
* go to the Firebase console https://console.firebase.google.com/u/0/ and create a new project
* enable and configure authentication (treasury is developed with Google auth only - but you shouldn't care)
* in database enable Cloud Firestore
* enable Functions
* enable Hosting

==== Update environment values
Go to the "Project Overview" and click "Add Firebase to my WebApp", grab the Firebase settings and update `treasury/src/environments/environment.dev.ts` with it:

[source,typescript]
-------------------
// NOTE other environment settings are stripped
export const environment = {
  firebase: {
    apiKey: '',
    authDomain: '',
    databaseURL: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: ''
  }
};
-------------------

==== Setup local enviroment
First, install firebase and firebase-tools globally (if not yet done):

[source]
--------
npm install -g firebase-tools firebase firebase-functions@latest firebase-admin@latest
--------

Go to the project's root folder (containing the folders `treasury`, `documents` and `functions`).

There create a file called `.firebaserc` and add the following content. Grab the `PROJECT-ID` from the Firebase console, under `Settings`:

[source]
--------
{
  "projects": {
    "default": "PROJECT-ID"
  }
}
--------
